name: '🐛 Bug Report'
description: Report a bug.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: 'Please read and follow the instructions before submitting an issue:'
  - type: markdown
    attributes:
      value: |
        - Read all our [Wiki](https://github.com/deep-foundation/documentation/wiki). It may contain information that helps you solve your issue.
        - Ensure your issue isn't already reported.
        - If you aren't sure that the issue is caused by Deep or you just need help, please use [![StackOverflow](https://badgen.net/badge/icon/stackoverflow?icon=stackoverflow&label&color=orange)](https://stackoverflow.com/questions/tagged/deep) or [![our Discord server](https://badgen.net/badge/icon/discord?icon=discord&label&color=purple)](https://discord.gg/deep-foundation).
        - Ensure it isn't already fixed in the latest versions.
  - type: markdown
    attributes:
      value: '⚠️👆 Feel free to these instructions before submitting the issue 👆⚠️'
  - type: textarea
    id: description
    attributes:
      label: 'Describe the bug'
      description: A clear and concise description of what the bug is.
    validations:
      required: false
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: 'What did you expect to happen?'
    validations:
      required: false
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: 'What actually happened?'
    validations:
      required: false
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Please link to a repository with a minimal reproduction and describe accurately how we can reproduce/verify the bug.
      placeholder: |
        Example steps (replace with your own):
        1. Clone my repo at https://github.com/<myuser>/example
        2. yarn install
        3. yarn test
        4. You should see the error come up
  - type: textarea
    id: envinfo
    attributes:
      label: Environment
      description: |
        Please paste the output of running `npx envinfo --system --npmPackages --markdown`. Do not forget to replace PACKAGE_NAME placeholder to actual package name.
        This will be automatically formatted as a code block, so no need for backticks.
      placeholder: |
        System:
          OS: Linux 5.10 Debian GNU/Linux 9 (stretch)
          CPU: (8) arm64
        Binaries:
          Node: 14.17.0 - /usr/local/bin/node
          Yarn: 1.22.5 - /usr/local/bin/yarn
          npm: 6.14.13 - /usr/local/bin/npm
        npmPackages:
          jest: 27.0.6 => 27.0.6
