name: '🪲 Bug Report'
description: Report a bug.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: 'Please read and follow the instructions before submitting an issue:'
  - type: markdown
    attributes:
      value: |
        - Read all our [Wiki](https://github.com/deep-foundation/documentation/wiki). It may contain information that helps you solve your issue.
        - To get help from humans and/or GPT-4 use [![StackOverflow](https://badgen.net/badge/icon/stackoverflow?icon=stackoverflow&label&color=orange)](https://stackoverflow.com/questions/tagged/deep) or [![our Discord server](https://badgen.net/badge/icon/discord?icon=discord&label&color=purple)](https://discord.gg/deep-foundation).
        - It would be nice if you ensure the issue isn't already reported.
        - It would be nice if you ensure it isn't already fixed in the latest versions.
  - type: markdown
    attributes:
      value: '⚠️👆 Feel free to these instructions before submitting the issue 👆⚠️'
  - type: textarea
    id: description
    attributes:
      label: 'Bug description'
      description: Give a clear and concise description of what the bug is.
    validations:
      required: false
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: 'What did you expect to happen?'
    validations:
      required: false
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: 'What actually happened?'
    validations:
      required: false
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Please link to a repository with a minimal reproduction and describe accurately how we can reproduce/verify the bug.
      placeholder: |
        Example steps (replace with your own):
        1. Clone my repo at https://github.com/<myuser>/example
        2. yarn install
        3. yarn test
        4. You should see the error come up
  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Describe another way to do what you have intended to do if you know any
    validations:
      required: false
  - type: textarea
    id: envinfo
    attributes:
      label: Environment
      description: |
        Please paste at least one of:
        * the Deep.Case App version
        * deep package version
        * the output of running `npx envinfo --system --npmPackages --markdown`. 
        Do not forget to replace PACKAGE_NAME placeholder to actual deep package name.
        This will be automatically formatted as a code block, so no need for backticks.
      render: shell
      placeholder: |
        Deep:
          Deep.Case App: 0.1.0-beta.12 (0.0.98)
          PACKAGE_NAME: 0.0.1
        System:
          OS: Linux 5.10 Debian GNU/Linux 9 (stretch)
          CPU: (8) arm64
        Binaries:
          Node: 14.17.0 - /usr/local/bin/node
          Yarn: 1.22.5 - /usr/local/bin/yarn
          npm: 6.14.13 - /usr/local/bin/npm
        npmPackages:
          jest: 27.0.6 => 27.0.6
