name: '🤔 Support or Question'
description: Get help.
labels: ['question']
body:
  - type: markdown
    attributes:
      value: 'Please read and follow the instructions before submitting an issue:'
  - type: markdown
    attributes:
      value: |
        - Read all our [Wiki](https://github.com/deep-foundation/documentation/wiki). It may contain information that helps you solve your issue.
        - Ensure your issue isn't already reported.
        - If you aren't sure that the issue is caused by Deep or you just need help, please use [![StackOverflow](https://badgen.net/badge/icon/stackoverflow?icon=stackoverflow&label&color=orange)](https://stackoverflow.com/questions/tagged/deep) or [![our Discord server](https://badgen.net/badge/icon/discord?icon=discord&label&color=purple)](https://discord.gg/deep-foundation).
        - If you're reporting a bug, ensure it isn't already fixed in the latest versions.
  - type: markdown
    attributes:
      value: '⚠️👆 Feel free to these instructions before submitting the issue 👆⚠️'
  - type: textarea
    id: description
    attributes:
      label: 'Describe the issue'
      description: A clear and concise description of what the issue is.
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: 'Example Code'
      description: Code snippet to illustrate your question
      render: js
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 'Expected behavior'
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: markdown
    attributes:
      value: Environment
  - type: input
    id: deep-version
    attributes:
      label: 'Deep Version'
      placeholder: 'e.g. 0.18.0'
  - type: input
    id: adapter-version
    attributes:
      label: 'Adapter Version'
      placeholder: 'e.g. XHR/HTTP'
  - type: input
    id: browser
    attributes:
      label: 'Browser'
      placeholder: 'e.g. Chrome, Safari'
  - type: input
    id: browser-version
    attributes:
      label: 'Browser Version'
      placeholder: 'e.g. 42'
  - type: input
    id: node-version
    attributes:
      label: 'Node.js Version'
      description: 'node --version'
      placeholder: 'e.g. 13.0.1'
  - type: input
    id: os
    attributes:
      label: 'OS'
      placeholder: 'e.g. iOS 16.0.2, OSX 12.6.0'
  - type: textarea
    id: other-version
    attributes:
      label: 'Additional Library Versions'
      placeholder: |
        e.g.
        React 16.7,
        React Native 0.58.0
      render: bash
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context/Screenshots'
      description: Add any other context about the problem here. If applicable, add screenshots to help explain.
      render: bash
    validations:
      required: false
